# Parameters to specify:

sample_name:
 -
 -

threads:

min_len_filtering:

max_len_filtering:

rrnas:

chosen_rrna: 18S_rRNA

db_location:

db_id: 0.7

db_query_cov: 0.9

enable_optional_taxonomy_format: true


# Optional parameters:

min_mean_quality_filering: 90

min_mean_quality_polishing: 20
