sample_name:
 - BAB10
 - MIK3

threads: 8

rrnas: 18S_rRNA:1000,28S_rRNA:400,5_8S_rRNA:90

chosen_rrna: 18S_rRNA

db_location: /home/chwalinska/pr2_database-5.0.0.fasta

db_id: 0.7

db_query_cov: 0.9

enable_optional_taxonomy_format: true
