```{r}
library('ggplot2')
library('reshape2')


```


```{r}
# Importing files:

minimap07 <- read.csv('./barcode07_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast07 <- read.csv('./barcode07_blast_taxonomy.tsv', header = TRUE, sep = '\t')

minimap08 <- read.csv('./barcode08_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast08 <- read.csv('./barcode08_blast_taxonomy.tsv', header = TRUE, sep = '\t')

minimap09 <- read.csv('./barcode09_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast09 <- read.csv('./barcode09_blast_taxonomy.tsv', header = TRUE, sep = '\t')

minimap10 <- read.csv('./barcode10_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast10 <- read.csv('./barcode10_blast_taxonomy.tsv', header = TRUE, sep = '\t')

minimap11 <- read.csv('./barcode11_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast11 <- read.csv('./barcode11_blast_taxonomy.tsv', header = TRUE, sep = '\t')

minimap12 <- read.csv('./barcode12_minimap_taxonomy.tsv', header = TRUE, sep = '\t')
blast12 <- read.csv('./barcode12_blast_taxonomy.tsv', header = TRUE, sep = '\t')

```


```{r}
# Filtering taxonomic levels: 

## Supergroup
m_sg07 <- minimap07$Supergroup
m_sg08 <- minimap08$Supergroup
m_sg09 <- minimap09$Supergroup
m_sg10 <- minimap10$Supergroup
m_sg11 <- minimap11$Supergroup
m_sg12 <- minimap12$Supergroup

b_sg07 <- blast07$Supergroup
b_sg08 <- blast08$Supergroup
b_sg09 <- blast09$Supergroup
b_sg10 <- blast10$Supergroup
b_sg11 <- blast11$Supergroup
b_sg12 <- blast12$Supergroup



## Division
m_dv07 <- minimap07$Division
m_dv08 <- minimap08$Division
m_dv09 <- minimap09$Division
m_dv10 <- minimap10$Division
m_dv11 <- minimap11$Division
m_dv12 <- minimap12$Division

b_dv07 <- blast07$Division
b_dv08 <- blast08$Division
b_dv09 <- blast09$Division
b_dv10 <- blast10$Division
b_dv11 <- blast11$Division
b_dv12 <- blast12$Division




```

```{r}
# Function

taxonomy_df <- function(unique_tax, tax_list, rang, name){
  header <- c(rang, name)
  counts <- vector()
  for (name in unique_tax){
    c <- 0
    for (tax in tax_list){
      if (name == tax){
        c <- c + 1
      }
    }
    counts <- append(counts, c)
  }
  df <- data.frame(unique_tax, counts)
  names(df) <- header
  return(df)
}



```


```{r}
# Getting unique

## Supergroup
m_sg_unique <- unique(c(m_sg07, m_sg08, m_sg09, m_sg10, m_sg11, m_sg12))
m_sg_unique

b_sg_unique <- unique(c(b_sg07, b_sg08, b_sg09, b_sg10, b_sg11, b_sg12))
b_sg_unique

## Division
m_dv_unique <- unique(c(m_dv07, m_dv08, m_dv09, m_dv10, m_dv11, m_dv12))
m_dv_unique

b_dv_unique <- unique(c(b_dv07, b_dv08, b_dv09, b_dv10, b_dv11, b_dv12))
b_dv_unique
```

```{r}
# Data frames


## Supergroup
df_m_sg07 <- taxonomy_df(m_sg_unique, m_sg07, 'supergroup', 'bar07')
df_m_sg08 <- taxonomy_df(m_sg_unique, m_sg08, 'supergroup', 'bar08')
df_m_sg09 <- taxonomy_df(m_sg_unique, m_sg09, 'supergroup', 'bar09')
df_m_sg10 <- taxonomy_df(m_sg_unique, m_sg10, 'supergroup', 'bar10')
df_m_sg11 <- taxonomy_df(m_sg_unique, m_sg11, 'supergroup', 'bar11')
df_m_sg12 <- taxonomy_df(m_sg_unique, m_sg12, 'supergroup', 'bar12')

df_m_sg <- data.frame(df_m_sg07, df_m_sg08[2], df_m_sg09[2], df_m_sg10[2], df_m_sg11[2], df_m_sg12[2])
df_m_sg



df_b_sg07 <- taxonomy_df(b_sg_unique, b_sg07, 'supergroup', 'bar07')
df_b_sg08 <- taxonomy_df(b_sg_unique, b_sg08, 'supergroup', 'bar08')
df_b_sg09 <- taxonomy_df(b_sg_unique, b_sg09, 'supergroup', 'bar09')
df_b_sg10 <- taxonomy_df(b_sg_unique, b_sg10, 'supergroup', 'bar10')
df_b_sg11 <- taxonomy_df(b_sg_unique, b_sg11, 'supergroup', 'bar11')
df_b_sg12 <- taxonomy_df(b_sg_unique, b_sg12, 'supergroup', 'bar12')

df_b_sg <- data.frame(df_b_sg07, df_b_sg08[2], df_b_sg09[2], df_b_sg10[2], df_b_sg11[2], df_b_sg12[2])
df_b_sg



## Division
df_m_dv07 <- taxonomy_df(m_dv_unique, m_dv07, 'division', 'bar07')
df_m_dv08 <- taxonomy_df(m_dv_unique, m_dv08, 'division', 'bar08')
df_m_dv09 <- taxonomy_df(m_dv_unique, m_dv09, 'division', 'bar09')
df_m_dv10 <- taxonomy_df(m_dv_unique, m_dv10, 'division', 'bar10')
df_m_dv11 <- taxonomy_df(m_dv_unique, m_dv11, 'division', 'bar11')
df_m_dv12 <- taxonomy_df(m_dv_unique, m_dv12, 'division', 'bar12')

df_m_dv <- data.frame(df_m_dv07, df_m_dv08[2], df_m_dv09[2], df_m_dv10[2], df_m_dv11[2], df_m_dv12[2])
df_m_dv




df_b_dv07 <- taxonomy_df(b_dv_unique, b_dv07, 'division', 'bar07')
df_b_dv08 <- taxonomy_df(b_dv_unique, b_dv08, 'division', 'bar08')
df_b_dv09 <- taxonomy_df(b_dv_unique, b_dv09, 'division', 'bar09')
df_b_dv10 <- taxonomy_df(b_dv_unique, b_dv10, 'division', 'bar10')
df_b_dv11 <- taxonomy_df(b_dv_unique, b_dv11, 'division', 'bar11')
df_b_dv12 <- taxonomy_df(b_dv_unique, b_dv12, 'division', 'bar12')

df_b_dv <- data.frame(df_b_dv07, df_b_dv08[2], df_b_dv09[2], df_b_dv10[2], df_b_dv11[2], df_b_dv12[2])
df_b_dv


```


```{r}
# Plots

## Supergroup
df_m_sg_melt <- melt(df_m_sg, value.name="Relative_abundance", variable.name="Barcode", na.rm=FALSE)

ggplot(df_m_sg_melt, aes(fill=supergroup, y=Relative_abundance, x= Barcode)) + 
  geom_bar(position="fill", stat="identity") +
  ggtitle('minimap2') +
  theme(plot.title = element_text(hjust = 0.5))
ggsave('minimap_supergroup_plot.pdf', plot = last_plot())  



df_b_sg_melt <- melt(df_b_sg, value.name="Relative_abundance", variable.name="Barcode", na.rm=FALSE)

ggplot(df_b_sg_melt, aes(fill=supergroup, y=Relative_abundance, x= Barcode)) + 
  geom_bar(position="fill", stat="identity") +
  ggtitle('blast') +
  theme(plot.title = element_text(hjust = 0.5))
ggsave('blast_supergroup_plot.pdf', plot = last_plot())  


## Division
df_m_dv_melt <- melt(df_m_dv, value.name="Relative_abundance", variable.name="Barcode", na.rm=FALSE)

ggplot(df_m_dv_melt, aes(fill=division, y=Relative_abundance, x= Barcode)) + 
  geom_bar(position="fill", stat="identity") +
  ggtitle('minimap2') +
  theme(legend.key.size = unit(0.5, 'cm')) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave('minimap_division_plot.pdf', plot = last_plot())  



df_b_dv_melt <- melt(df_b_dv, value.name="Relative_abundance", variable.name="Barcode", na.rm=FALSE)

ggplot(df_b_dv_melt, aes(fill=division, y=Relative_abundance, x= Barcode)) + 
  geom_bar(position="fill", stat="identity") +
  ggtitle('blast') +
  theme(legend.key.size = unit(0.5, 'cm')) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave('blast_division_plot.pdf', plot = last_plot()) 
```




